# Beispielkonfiguration für rss_synd.tcl im TOML-Format

[defaults]
announce-output = 3
trigger-output = 3
remove-empty = 1
trigger-type = "0:2"
announce-type = 0
max-depth = 5
evaluate-tcl = 0
update-interval = 30
output-order = 0
log-mode = "immediate"
log-interval = 5
timeout = 60000
channels = "#channel"
trigger = "!rss @@feedid@@"
output = "[\u0002@@channel!title@@@@title@@\u0002] @@item!title@@@@entry!title@@@@published@@ - @@item!link@@@@entry!link!=href@@"
user-agent = [
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
  "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1",
  "Mozilla/5.0 (iPad; CPU OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1",
  "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro Build/AP2A.240605.024) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.72 Mobile Safari/537.36",
  "Mozilla/5.0 (Linux; Android 14; SM-S928B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36"
]
user-agent-rotate = "list"
https-allow-legacy = 0

[feeds.msbulletins]
url = "http://technet.microsoft.com/en-us/security/rss/bulletin"
channels = "#channel"
database = "/path to dir/msbulletins.db"
output = "[\u000312\u0002MS Security bulletins\u0002\u0003] \u000310\u0002@@item!title@@\u0002\u0003 - @@item!link@@"
trigger = "!msbulletins"
announce-output = 5
trigger-output = 5
update-interval = 10
output-order = 0
